# YAML reference => https://rebrand.ly/az-devops-yaml

name: $(BuildDefinitionName).$(Date:yyyyMMdd)$(Rev:.rr) 
# ^^ https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops&viewFallbackFrom=vsts&tabs=yaml#build-number-format

trigger:
  batch: true # Queue up builds, only 1 at a time
  branches:
    include:
      - master
      - feature/*
    exclude:
      - foobar/*
  # paths:
  #   include:
  #     - 'pharmacy'

# variables:
# - name: state.key
#   value: 'TFSTATE'
# - name: terraform.path
#   value: 'SOMEPATH/DEV/AKS'
# - group: 'KEY-VAULT-VAR-GROUP'
# - group: 'STANDARD-VAR-GROUP'

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  clean: true
  persistCredentials: true
  displayName: 'Checkout repo'

# Move to central repo to share steps => https://rebrand.ly/az-devops-step-templates
- template: az-devops-templates/install-tf.yml

- template: az-devops-templates/configure-tf.yml

- script: echo Done with build
  displayName: 'Announce complete....'
