# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    TIMESTAMP="echo $(TZ=America/New_York date +"%m-%d-%y %r" | sed -e 's/\([0-9][0-9]:[0-9][0-9]\):[0-9][0-9]/\1/')"
    echo "$(eval TIMESTAMP) \tInstalling Terraform binary"
    apt-get install unzip wget
    wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
    unzip terraform_0.11.10_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    TF_VERSION=$(terraform --version)
    echo -e "$(eval TIMESTAMP) \tInstalled Terraform binary\n\t\tTerraform version => $TF_VERSION"
  displayName: 'Install Terraform binary'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
